# Generated by Django 5.1.3 on 2024-12-09 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('study_program', models.TextField()),
                ('course', models.IntegerField()),
                ('head_of_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('validation', models.BooleanField()),
                ('parameters', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_question_manage.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_question_manage.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('MO', 'Multiple Option'), ('TF', 'True or False'), ('E', 'Essay')], max_length=2)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('D', 'Difficult')], max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.teacher')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_question_manage.topic')),
            ],
        ),
    ]
