# Generated by Django 5.1.3 on 2025-01-16 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_question_manage', '0003_subject_teachers_subject_alter_exam_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_question_manage.subject'),
        ),
    ]
