# Generated by Django 5.1.3 on 2025-01-26 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_course_alter_student_course'),
        ('questions', '0006_alter_subject_course_remove_exam_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('questions', models.ManyToManyField(related_name='exams', to='questions.question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.teacher')),
                ('validation_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_teacher', to='account.teacher')),
            ],
        ),
    ]
