# Generated by Django 5.1.3 on 2025-01-27 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_course_alter_student_course'),
        ('exams', '0001_initial'),
        ('questions', '0006_alter_subject_course_remove_exam_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('observation', models.CharField(max_length=500)),
                ('exam_Done', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examdone')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='ValidatedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('observations', models.CharField(max_length=500)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='examdone',
            name='validated_exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.validatedexam'),
        ),
    ]
