# Generated by Django 5.1.3 on 2025-01-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examdone_examquestionresponse_validatedexam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestionresponse',
            name='observation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
