# Generated by Django 5.1.3 on 2025-01-30 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_examquestionresponse_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examdone',
            name='validated_exam',
        ),
        migrations.AddField(
            model_name='exam',
            name='state',
            field=models.CharField(choices=[('V', 'Validated'), ('R', 'Rejected'), ('P', 'Pending')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='examdone',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.exam'),
        ),
        migrations.CreateModel(
            name='AssignedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('observations', models.CharField(max_length=500)),
                ('checked', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
            ],
        ),
        migrations.DeleteModel(
            name='ValidatedExam',
        ),
    ]
