# Generated by Django 5.1.3 on 2025-01-30 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_course_alter_student_course'),
        ('exams', '0004_remove_examdone_validated_exam_exam_state_and_more'),
        ('questions', '0006_alter_subject_course_remove_exam_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('finalnote', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='examquestionresponse',
            name='observation',
        ),
        migrations.AddField(
            model_name='examquestionresponse',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='examquestionresponse',
            constraint=models.CheckConstraint(condition=models.Q(('note__gte', 0), ('note__lte', 100)), name='note_range'),
        ),
        migrations.AddField(
            model_name='examgrade',
            name='examdone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examdone'),
        ),
        migrations.AddField(
            model_name='examgrade',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.teacher'),
        ),
        migrations.AddConstraint(
            model_name='examgrade',
            constraint=models.CheckConstraint(condition=models.Q(('finalnote__gte', 0), ('finalnote__lte', 100)), name='finalnote_range'),
        ),
    ]
