# Generated by Django 5.1.3 on 2025-01-30 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_course_alter_student_course'),
        ('exams', '0005_examgrade_remove_examquestionresponse_observation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReevaluatedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('examgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examgrade')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.teacher')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('note__gte', 0), ('note__lte', 100)), name='reevaluated_note_range')],
            },
        ),
    ]
