# Generated by Django 5.1.3 on 2025-01-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_reevaluatedexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='validation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
