# Generated by Django 5.1.3 on 2025-02-01 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_validation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examgrade',
            name='examdone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exams.examdone'),
        ),
        migrations.AlterField(
            model_name='reevaluatedexam',
            name='examgrade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exams.examgrade'),
        ),
    ]
