# Generated by Django 5.1.3 on 2025-01-16 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_student_options_alter_teacher_options_and_more'),
        ('questions', '0002_alter_subject_head_of_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teachers_subject',
            field=models.ManyToManyField(related_name='subjects', to='account.teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.teacher'),
        ),
        migrations.AlterField(
            model_name='question',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.teacher'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.topic'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='head_of_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.teacher'),
        ),
    ]
